sudo: required
services:
  - docker
before_install:
  - docker build -t davidgeismar/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run davidgeismsar/react-test npm test -- --coverage

after_success:
  - docker build -t davidgeismar/multi-client ./client
  - docker build -t davidgeismar/multi-nginx ./nginx
  - docker build -t davidgeismar/multi-server ./server
  - docker build -t davidgeismar/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidgeismar/multi-client
  - docker push davidgeismar/multi-nginx
  - docker push davidgeismar/multi-server
  - docker push davidgeismar/multi-worker
